### ISSUE TITLE
RunMojo throws IOException when retestAll is false

### ISSUE THREAD

**Issue by yujinz** [TestingResearchIllinois/starts#43]
When retestAll is false, getJarToChecksumMapping will be called in RunMojo, and it throws an exception.

Reproduce: After the initial run `mvn starts:starts` which runs all tests, modify some code of the project being built, so that STARTS is supposed to run a subset of the tests in the next build. Then run `mvn starts:starts` again, and I can get the error below.

java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at edu.illinois.starts.helpers.Writer.getJarToChecksumMapping(Writer.java:233)
	at edu.illinois.starts.jdeps.RunMojo.hasSameJarChecksum(RunMojo.java:161)
	at edu.illinois.starts.jdeps.RunMojo.run(RunMojo.java:95)
	at edu.illinois.starts.jdeps.RunMojo.execute(RunMojo.java:82)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by owolabileg** [comment]
@milicahtanovic Is this from #13? I marked this as a bug. Please take a look.

**Comment by milicahtanovic** [comment]
@yujinz Can you clarify in the "Reproduce" step, what kind of modifications did you make? The error indicates a directory on the classpath other than classes and test-classes.

**Comment by yujinz** [comment]
It could be any modification, for example, modifying the value of a string. I did something similar to this video: https://youtu.be/PCNtk8jphrM.

**Comment by milicahtanovic** [comment]
@yujinz So you are saying that every time you make a change you get this exception?

**Comment by yujinz** [comment]
@milicahtanovic The only project that I did not get an exception after making a change is this: https://github.com/gabrielf/maven-samples/tree/master/single-module. I guess the reason is that there is only one source file and one test file, so any modification will affect all the files.
For other projects like open-mrs and commons-functor, I always get the exception after making a change.

**Comment by milicahtanovic** [comment]
@yujinz Ok, thanks for the clarification. I will fix this.

**Comment by milicahtanovic** [comment]
@yujinz Can you provide the exact repro steps, line by line for project commons-functor (because this one doesn't run for too long)? The change you make to the file you can put under comment like this: #<file-name> -> <change>
I tried different projects and I didn't get the bug.
