### ISSUE TITLE
Not supporting project with a mixture usage of Junit4 and Junit5

### ISSUE THREAD

**Issue by sweetStreet** [TestingResearchIllinois/starts#66]
I downloaded commons-collections with the latest version whose SHA is 7e953fd6dd0d35e19239169edf72298be02d550e. Then I revised pom.xml and added starts plugin.
The command I used is "mvn starts:starts -DstartsLogging=FINEST -DdepFormat=CLZ -Drat.skip"

java version is 1.8
maven version is 3.6.3
in pom.xml, its jdk version is 1.8

The error message is
```
Users/home/.m2/repository/org/junit/vintage/junit-vintage-engine/5.6.2/junit-vintage-engine-5.6.2.jar,
/Users/home/.m2/repository/junit/junit/4.13/junit-4.13.jar,
/Users/home/.m2/repository/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar,
/Users/home/.m2/repository/org/easymock/easymock/4.2/easymock-4.2.jar,
/Users/home/.m2/repository/org/objenesis/objenesis/3.1/objenesis-3.1.jar,
/Users/home/.m2/repository/org/apache/commons/commons-lang3/3.11/commons-lang3-3.11.jar,
/Users/home/.m2/repository/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar,
/Users/home/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar]
FINE: [PROFILE] updateForNextRun(getSureFireClassPath): 0.014 FINE:
[PROFILE] updateForNextRun(pathToString): 0.000 FINEST: @@Excludes:
[**/*$*, **/TestUtils.java, **/Abstract*.java, **/BulkTest.java]
FINEST: @@Includes: [**/*Test.java] FINE: [PROFILE]
updateForNextRun(setIncludesExcludes): 0.001 FINE: [PROFILE]
updateForNextRun(getTestClasses): 0.064 FINE: [PROFILE]
updateForNextRun(createClassLoader): 0.004 FINE: JDEPS ARGS:[-v,
/Users/home/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.6.2/junit-jupiter-api-5.6.2.jar]
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE [INFO]
------------------------------------------------------------------------
[INFO] Total time: 20.107 s [INFO] Finished at:
2020-10-20T23:51:33-05:00 [INFO]
------------------------------------------------------------------------
--------------------------------------------------- constituent[0]:
file:/Users/home/apache-maven/conf/logging/ constituent[1]:
file:/Users/home/apache-maven/lib/maven-plugin-api-3.6.3.jar
constituent[2]:
file:/Users/home/apache-maven/lib/maven-compat-3.6.3.jar
constituent[3]:
file:/Users/home/apache-maven/lib/maven-resolver-util-1.4.1.jar
constituent[4]:
file:/Users/home/apache-maven/lib/plexus-component-annotations-2.1.0.jar
constituent[5]:
file:/Users/home/apache-maven/lib/maven-settings-builder-3.6.3.jar
constituent[6]:
file:/Users/home/apache-maven/lib/plexus-cipher-1.7.jar
constituent[7]:
file:/Users/home/apache-maven/lib/plexus-interpolation-1.25.jar
constituent[8]:
file:/Users/home/apache-maven/lib/maven-resolver-spi-1.4.1.jar
constituent[9]:
file:/Users/home/apache-maven/lib/guice-4.2.1-no_aop.jar
constituent[10]:
file:/Users/home/apache-maven/lib/maven-artifact-3.6.3.jar
constituent[11]:
file:/Users/home/apache-maven/lib/maven-resolver-provider-3.6.3.jar
constituent[12]: file:/Users/home/apache-maven/lib/cdi-api-1.0.jar
constituent[13]:
file:/Users/home/apache-maven/lib/maven-slf4j-provider-3.6.3.jar
constituent[14]:
file:/Users/home/apache-maven/lib/plexus-utils-3.2.1.jar
constituent[15]:
file:/Users/home/apache-maven/lib/plexus-sec-dispatcher-1.4.jar
constituent[16]:
file:/Users/home/apache-maven/lib/maven-repository-metadata-3.6.3.jar
constituent[17]:
file:/Users/home/apache-maven/lib/commons-cli-1.4.jar
constituent[18]:
file:/Users/home/apache-maven/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[19]: file:/Users/home/apache-maven/lib/commons-io-2.5.jar
constituent[20]: file:/Users/home/apache-maven/lib/jansi-1.17.1.jar
constituent[21]:
file:/Users/home/apache-maven/lib/maven-model-builder-3.6.3.jar
constituent[22]:
file:/Users/home/apache-maven/lib/maven-embedder-3.6.3.jar
constituent[23]:
file:/Users/home/apache-maven/lib/wagon-file-3.3.4.jar
constituent[24]:
file:/Users/home/apache-maven/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[25]:
file:/Users/home/apache-maven/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[26]:
file:/Users/home/apache-maven/lib/maven-settings-3.6.3.jar
constituent[27]:
file:/Users/home/apache-maven/lib/maven-model-3.6.3.jar
constituent[28]:
file:/Users/home/apache-maven/lib/maven-resolver-api-1.4.1.jar
constituent[29]:
file:/Users/home/apache-maven/lib/jcl-over-slf4j-1.7.29.jar
constituent[30]:
file:/Users/home/apache-maven/lib/wagon-http-3.3.4-shaded.jar
constituent[31]:
file:/Users/home/apache-maven/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[32]:
file:/Users/home/apache-maven/lib/slf4j-api-1.7.29.jar
constituent[33]:
file:/Users/home/apache-maven/lib/maven-builder-support-3.6.3.jar
constituent[34]: file:/Users/home/apache-maven/lib/jsoup-1.12.1.jar
constituent[35]:
file:/Users/home/apache-maven/lib/wagon-provider-api-3.3.4.jar
constituent[36]:
file:/Users/home/apache-maven/lib/maven-shared-utils-3.2.1.jar
constituent[37]:
file:/Users/home/apache-maven/lib/maven-resolver-impl-1.4.1.jar
constituent[38]:
file:/Users/home/apache-maven/lib/maven-core-3.6.3.jar
constituent[39]: file:/Users/home/apache-maven/lib/javax.inject-1.jar
constituent[40]:
file:/Users/home/apache-maven/lib/commons-lang3-3.8.1.jar
constituent[41]:
file:/Users/home/apache-maven/lib/guava-25.1-android.jar
constituent[42]: file:/Users/home/apache-maven/lib/jsr250-api-1.0.jar
--------------------------------------------------- Exception in
thread "main" java.lang.InternalError: Missing message:
warn.skipped.entry at
com.sun.tools.jdeps.JdepsTask.getMessage(JdepsTask.java:709) at
com.sun.tools.jdeps.JdepsTask.warning(JdepsTask.java:673) at
com.sun.tools.jdeps.JdepsTask.findDependencies(JdepsTask.java:563) at
com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:324) at
com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:306) at
com.sun.tools.jdeps.Main.run(Main.java:63) at
edu.illinois.starts.helpers.RTSUtil.runJdeps(RTSUtil.java:78) at
edu.illinois.starts.helpers.Cache.checkMissingJarsInJDKCache(Cache.java:78)
at
edu.illinois.starts.helpers.Cache.loadM2EdgesFromCache(Cache.java:48)
at
edu.illinois.starts.jdeps.BaseMojo.prepareForNextRun(BaseMojo.java:227)
at
edu.illinois.starts.jdeps.DiffMojo.prepareForNextRun(DiffMojo.java:33)
at
edu.illinois.starts.jdeps.DiffMojo.updateForNextRun(DiffMojo.java:103)
at edu.illinois.starts.jdeps.RunMojo.run(RunMojo.java:81) at
edu.illinois.starts.jdeps.RunMojo.execute(RunMojo.java:62) at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at
org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:355)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
at
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305) at
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192) at
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105) at
org.apache.maven.cli.MavenCli.execute(MavenCli.java:957) at
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289) at
org.apache.maven.cli.MavenCli.main(MavenCli.java:193) at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498) at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
at
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)~

```

**Comment by sweetStreet** [comment]
It contains the error because I used version 1.3 according to readme. When I downloaded the source code and compile, I found that 1.4-SNAPSHOT works well on junit5 projects.
